version: "3.7"
services:
  app:
    image: node:18-alpine
    build: .
    container_name: "myapp"
    restart: always
    env_file:
      - "./.env"
    ports:
      - "3000:3000"
    extra_hosts:
      - "networkLocalhost:192.168.0.0"
